# Generated by Django 4.0.6 on 2022-07-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=2)),
                ('details', models.TextField(max_length=300)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.city')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.countrie')),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.district')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.state')),
            ],
        ),
    ]
