# Generated by Django 4.0.6 on 2022-07-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_countrie_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cities',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='countries',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='districts',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='states',
            new_name='state',
        ),
    ]
