# Generated by Django 4.0.6 on 2022-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='details',
            field=models.TextField(),
        ),
    ]
