# Generated by Django 4.0.6 on 2022-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_rename_cities_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
