# Generated by Django 4.0.6 on 2022-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrows',
            name='row',
            field=models.CharField(max_length=20),
        ),
    ]
