# Generated by Django 4.0.6 on 2022-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_seatrows_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrows',
            name='seat_count',
            field=models.PositiveIntegerField(),
        ),
    ]
