# Generated by Django 4.0.6 on 2022-08-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_seatrows_seatrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.room'),
        ),
    ]
