# Generated by Django 4.0.6 on 2022-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
