# Generated by Django 4.0.6 on 2022-07-18 00:40

from django.db import migrations, models
import movie_sessions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[movie_sessions.validators.PriceValidators.validate_positive, movie_sessions.validators.DateValidators.session_day_cannot_be_before_today]),
        ),
    ]
