# Generated by Django 4.0.6 on 2022-07-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0003_alter_moviesession_price'),
        ('movie_sessions', '0003_rename_is_avaliable_sessionseat_is_available'),
    ]

    operations = [
    ]
