# Generated by Django 4.0.6 on 2022-07-18 22:31

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0004_merge_20220718_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[utils.validators.PriceValidators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='session_datetime',
            field=models.DateTimeField(validators=[utils.validators.DateValidators.session_day_cannot_be_before_today]),
        ),
    ]
