# Generated by Django 4.0.6 on 2022-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_agegroup_distributor_genre_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='content',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
