# Generated by Django 4.0.6 on 2022-07-18 20:44

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_image_video_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=image_optimizer.fields.OptimizedImageField(default='', upload_to='movies/images/2022-07-18 20:44:38.119206+00:00/'),
            preserve_default=False,
        ),
    ]
