# Generated by Django 4.0.6 on 2022-07-18 20:46

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_image_url_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=image_optimizer.fields.OptimizedImageField(upload_to='movies/images/'),
        ),
    ]
