# Generated by Django 4.0.6 on 2022-07-19 11:43

from django.db import migrations
import image_optimizer.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=image_optimizer.fields.OptimizedImageField(upload_to='', validators=[utils.validators.UploadValidators.validate_file_size]),
        ),
    ]
