# Generated by Django 4.0.6 on 2022-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_agegroup_minimum_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agegroup",
            name="minimum_age",
            field=models.IntegerField(
                choices=[
                    (0, "L"),
                    (10, "10"),
                    (12, "12"),
                    (14, "14"),
                    (16, "16"),
                    (18, "18"),
                ],
                default=0,
            ),
        ),
    ]
