# Generated by Django 4.0.6 on 2022-08-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movie'),
        ),
    ]
