# Generated by Django 4.0.6 on 2022-07-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_movie_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_seats",
                to="tickets.seat",
            ),
        ),
    ]
