# Generated by Django 4.0.6 on 2022-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_sessionseat_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionSeat',
        ),
    ]
