# Generated by Django 4.0.6 on 2022-07-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0004_alter_sessionseat_seat'),
        ('tickets', '0006_delete_sessionseat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
