# Generated by Django 4.0.6 on 2022-07-18 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[utils.validators.PriceValidators.validate_positive])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_control', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaFinancialControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[utils.validators.PriceValidators.validate_positive])),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[utils.validators.PriceValidators.validate_positive])),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_control', to='cinemas.cinema')),
            ],
        ),
    ]
