# Generated by Django 4.0.6 on 2022-07-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_controls', '0001_initial'),
        ('cinemas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancialcontrol',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_control', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cinemafinancialcontrol',
            name='cinema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_control', to='cinemas.cinema'),
        ),
    ]
