# Generated by Django 4.0.6 on 2022-07-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_controls', '0002_remove_userfinancialcontrol_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemafinancialcontrol',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='cinemafinancialcontrol',
            name='income',
        ),
    ]
